services:
  redis:
    build: .
    image: redis-docker
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - redis_network
    
volumes:
  redis-data:
    driver: local

networks:
  redis_network:
    driver: bridge